cookie_story_blog_homepage:
    path:     /
    defaults: { _controller: CookieStoryBlogBundle:Default:index }

cookie_story_blog_feed:
    path:     /feed
    defaults: { _controller: CookieStoryBlogBundle:Default:feed }

cookie_story_blog_connexion:
    path:     /admin/connect
    defaults: { _controller: cookie_story_blog.admin_controller:connexion }

cookie_story_blog_upload:
    path:     /upload
    defaults: { _controller: CookieStoryBlogBundle:Default:upload }

cookie_story_blog_getrecette:
    path: /recette/find
    defaults: { _controller: cookie_story_blog.recette_controller:getRecette }

cookie_story_blog_gettag:
    path: /tag/find
    defaults: { _controller: cookie_story_blog.recette_controller:getTag }

cookie_story_blog_getlisterecettebytag:
    path: /recette/tag
    defaults: { _controller: cookie_story_blog.recette_controller:getListeRecetteByTag }

cookie_story_blog_getlisterecette:
    path: /recette/liste
    defaults: { _controller: cookie_story_blog.recette_controller:getListeRecette }

cookie_story_blog_getlistetags:
    path: /tags/liste
    defaults: { _controller: cookie_story_blog.recette_controller:getListeTags }

cookie_story_blog_saverecette:
    path: /recette/save
    defaults: { _controller: cookie_story_blog.recette_controller:saveRecette }

cookie_story_blog_deleterecette:
    path: /recette/delete
    defaults: { _controller: cookie_story_blog.recette_controller:deleteRecette }

cookie_story_blog_savecommentaire:
    path: /recette/saveCommentaire
    defaults: { _controller: cookie_story_blog.recette_controller:saveCommentaire }

cookie_story_blog_addtag:
    path: /saveTag
    defaults: { _controller: cookie_story_blog.recette_controller:addTag }

cookie_story_blog_removetag:
    path: /removeTag
    defaults: { _controller: cookie_story_blog.recette_controller:removeTag }

cookie_story_blog_addtagtorecette:
    path: /saveTagToRecette
    defaults: { _controller: cookie_story_blog.recette_controller:addTagToRecette }

cookie_story_blog_removetagfromrecette:
    path: /removeTagFromRecette
    defaults: { _controller: cookie_story_blog.recette_controller:removeTagFromRecette }
